name: Automated Lighthouse Report

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"]  # Replace with the actual name of the triggering workflow
    types:
      - completed

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node scripts/main.mjs

      - name: Archive Artifacts
        if: always()  # Ensure this runs even if the script fails
        uses: actions/upload-artifact@v4
        with:
          name: output-artifacts
          path: auto_*
